/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ui;

import com.dao.BanVeDAO;
import com.mode.BanVe;
import com.utils.Auth;
import com.utils.MsgBox;
import com.utils.XImage;
import com.utils.exBV;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kim Khanh
 */
public class BanVeJFrame extends javax.swing.JFrame {

    /**
     * Creates new form BanVeJFrame
     */
    public BanVeJFrame() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTien = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhongVe = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cboKhuVuc = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rdoTreEm = new javax.swing.JRadioButton();
        rdoNguoiLon = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        btnDangXuat = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnInVe = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblNgay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bán Vé");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Phòng Vé");

        jLabel5.setText("Tổng tiền:");

        lblTien.setText("0đ");

        tblPhongVe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Khu vực", "Mã NV", "Giá vé", "Loại vé", "Số Lượng", "Tổng", "Ngày"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPhongVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhongVeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPhongVe);

        jLabel1.setText("Khu vực:");

        cboKhuVuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ve Vao Cong", "Ve Tro Choi" }));

        jLabel2.setText("Số Lượng:");

        txtSoLuong.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSoLuongFocusLost(evt);
            }
        });

        jLabel3.setText("Loại vé:");

        buttonGroup1.add(rdoTreEm);
        rdoTreEm.setSelected(true);
        rdoTreEm.setText("Trẻ em");
        rdoTreEm.setBorderPainted(true);

        buttonGroup1.add(rdoNguoiLon);
        rdoNguoiLon.setText("Người lớn");
        rdoNguoiLon.setAutoscrolls(true);
        rdoNguoiLon.setBorderPainted(true);

        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sticker/Exit.png"))); // NOI18N
        btnDangXuat.setText("Đăng Xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        jPanel1.add(btnDangXuat);

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sticker/Stop.png"))); // NOI18N
        btnThoat.setText("Thoát");
        jPanel1.add(btnThoat);

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sticker/Delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel1.add(btnXoa);

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sticker/Notes.png"))); // NOI18N
        btnSua.setText("sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSua);

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sticker/Add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel1.add(btnThem);

        btnInVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sticker/Print.png"))); // NOI18N
        btnInVe.setText("In vé");
        btnInVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInVeActionPerformed(evt);
            }
        });
        jPanel1.add(btnInVe);

        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sticker/No.png"))); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        jPanel1.add(btnHuy);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Icon/logo.png"))); // NOI18N

        lblNgay.setText("Ngày");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTien))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtSoLuong))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel3))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rdoTreEm, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(rdoNguoiLon, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(cboKhuVuc, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41)
                        .addComponent(lblNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel6)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNgay))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cboKhuVuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rdoTreEm)
                                .addComponent(rdoNguoiLon))
                            .addComponent(jLabel3)))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblTien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        this.Sua();
        this.hienthiTable();
        this.setIconImage(XImage.getAppIcon());
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        this.them();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnInVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInVeActionPerformed
        try {
            this.insert();
            this.xuat();
            this.xoaDataTbale();
        } catch (Exception e) {
            MsgBox.alert(this, "Thao tac sai");
        }
        
       
    }//GEN-LAST:event_btnInVeActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        this.clearForm();
        this.xoaDataTbale();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void tblPhongVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhongVeMouseClicked
        hiemthiForm();
    }//GEN-LAST:event_tblPhongVeMouseClicked

    private void txtSoLuongFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSoLuongFocusLost
        if(rdoNguoiLon.isSelected()){
            try {
                int sl = Integer.parseInt(txtSoLuong.getText());
                float t = (sl * 50000);
                String tong = String.format("%.1f", t);
                lblTien.setText(tong);
            } catch (Exception e) {
                
            }
        }else{
            try {
                int sl = Integer.parseInt(txtSoLuong.getText());
                float t = (sl * 30000);
                String tong = String.format("%.1f", t);
                lblTien.setText(tong);
            } catch (Exception e) {
               
            }
        }
    }//GEN-LAST:event_txtSoLuongFocusLost

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        this.dangXuat();
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        this.Xoa();
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BanVeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BanVeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BanVeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BanVeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BanVeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnInVe;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboKhuVuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNgay;
    private javax.swing.JLabel lblTien;
    private javax.swing.JRadioButton rdoNguoiLon;
    private javax.swing.JRadioButton rdoTreEm;
    private javax.swing.JTable tblPhongVe;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables
ArrayList<BanVe> list = new ArrayList<BanVe>();
BanVeDAO dao = new BanVeDAO();
    void init(){
        setLocationRelativeTo(null);
        starDongHo();
    }
     private void starDongHo() {
        new Timer(1000, new ActionListener() {
            @Override
            //cứ 1000ms sẽ gọi hàm 1 lần
            public void actionPerformed(ActionEvent e) {
                // lấy thời gian hệ thống ra
                Date now = new Date();
                //Chuyển đổi sang chuổi giờ phút giây
                SimpleDateFormat fm = new SimpleDateFormat("dd-MM-yyyy hh-mm-ss a");
                
                lblNgay.setText(fm.format(new Date()));
                //a: sáng chiều
                //String text = format.format(now);
               // lblngay.setText(text);
            }
        }).start();
    }
    private void Xoa(){
        try{
        int r = tblPhongVe.getSelectedRow();
        list.remove(r);
        this.hienthiTable();
        }catch(Exception e){
            MsgBox.alert(this, "Vui lòng chọn dòng để xóa");
        }
    }
    private void them() {
        try {
            BanVe ln = new BanVe();

            ln.setKhuvuc(String.valueOf(cboKhuVuc.getSelectedItem()));
            ln.setManv(Auth.user.getManv());
            if(rdoNguoiLon.isSelected()){
                ln.setGiave(Float.parseFloat("50000"));
            }else{
                ln.setGiave(Float.parseFloat("30000"));
            }
            ln.setLoaive(rdoNguoiLon.isSelected());
            ln.setSoluong(Integer.parseInt(txtSoLuong.getText()));
            ln.setTong(Float.parseFloat(lblTien.getText()));
            ln.setGioTaoVe(lblNgay.getText());
            //ln.setNgayxuat(ngayxuat);
            list.add(ln);
            this.hienthiTable();
            this.cleartxt();
        } catch (Exception e) {
            MsgBox.alert(this, "Thông tin sai!");
        }
    }
    private void hienthiTable(){
        DefaultTableModel model = (DefaultTableModel) tblPhongVe.getModel();
            model.setRowCount(0);

            for (BanVe lnhuan : list) {
                model.addRow(new Object[]{
                    lnhuan.getKhuvuc(),
                    lnhuan.getManv(),
                    lnhuan.getGiave(),
                    lnhuan.getLoaive() ? "Người Lớn" : "Trẻ Em",
                    lnhuan.getSoluong(),
                    lnhuan.getTong(),
                    lnhuan.getGioTaoVe(),
                });
            }
    }
    private void hiemthiForm(){
        
        int r = tblPhongVe.getSelectedRow();
        cboKhuVuc.setSelectedItem(tblPhongVe.getValueAt(r, 0));
        txtSoLuong.setText(tblPhongVe.getValueAt(r, 4).toString());
        if (tblPhongVe.getValueAt(r, 3).equals("Trẻ Em")) {
            rdoTreEm.setSelected(true);
        }else{
            rdoNguoiLon.setSelected(true);
        }
        lblTien.setText(tblPhongVe.getValueAt(r, 5).toString());
        lblNgay.setText(tblPhongVe.getValueAt(r, 6).toString());
    }
    private void insert() {
       try {
            for (int i = 0; i < tblPhongVe.getRowCount(); i++) {
                BanVe bv = new BanVe();
                
                bv.setKhuvuc(tblPhongVe.getValueAt(i, 0).toString());
                bv.setManv(tblPhongVe.getValueAt(i, 1).toString());
                bv.setGiave(Float.parseFloat(tblPhongVe.getValueAt(i, 2).toString()));
                if (tblPhongVe.getValueAt(i, 3).equals("Trẻ Em")) {
                    bv.setLoaive(rdoTreEm.isSelected());
                } else {
                    bv.setLoaive(rdoNguoiLon.isSelected());
                }
                bv.setGioXuatVe(new Date());
                bv.setSoluong(Integer.parseInt(tblPhongVe.getValueAt(i, 4).toString()));
                bv.setTong(Float.parseFloat(tblPhongVe.getValueAt(i, 5).toString()));
                
                bv.setGioTaoVe(tblPhongVe.getValueAt(i, 6).toString());
                dao.insert(bv);
                this.clearForm();
            }
            
        } catch (Exception e) {
           MsgBox.alert(this, "In thất bại!!!");
        }
    }
    void xoaDataTbale() {
        DefaultTableModel model = (DefaultTableModel) tblPhongVe.getModel();
            model.setRowCount(0);
            list.removeAll(list);
    }
    void cleartxt(){
        txtSoLuong.setText("");
        rdoTreEm.setSelected(true);
    }
    void setForm(BanVe bv){
        cboKhuVuc.setSelectedItem(bv.getKhuvuc());
        rdoTreEm.setSelected(bv.getLoaive());
        rdoNguoiLon.setSelected(!bv.getLoaive());
        txtSoLuong.setText(String.valueOf(bv.getSoluong()));
        lblTien.setText(String.valueOf(bv.getTong()));
    }
    void clearForm(){
        cboKhuVuc.setSelectedIndex(0);
        rdoTreEm.setSelected(true);
        txtSoLuong.setText("");
        lblTien.setText("0đ");
    }
    private void dangXuat(){
        Auth.clear();
        this.dispose();
        new DangNhapJDialog(this, true).setVisible(true);
    }
    private void Sua(){
        try{
        int r = tblPhongVe.getSelectedRow();
        BanVe bV = list.get(r);
        bV.setKhuvuc(String.valueOf(cboKhuVuc.getSelectedItem()));
        bV.setLoaive(rdoNguoiLon.isSelected());
        if (rdoNguoiLon.isSelected()) {
            bV.setGiave(Float.parseFloat("50000"));
        } else {
            bV.setGiave(Float.parseFloat("30000"));
        }
        bV.setSoluong(Integer.parseInt(txtSoLuong.getText()));
        bV.setTong(Float.parseFloat(lblTien.getText()));
        bV.setGioTaoVe(lblNgay.getText());
        }catch(Exception e){
            MsgBox.alert(this, "Thao tác sai");
        }
    }
    
    void xuat(){
        for (BanVe bv : list) {
        
        Object[] info = new Object[7];
        
        info[0] = bv.getKhuvuc();
        info[1] = bv.getManv();
        info[2] = bv.getGiave();
        info[3] = bv.getLoaive()?"Nguoi Lon":"Tre Em";
        info[4] = bv.getSoluong();
        info[5] = bv.getTong();
        info[6] = bv.getGioTaoVe();
        
        boolean res = new exBV().createPDFFile(bv.getGioTaoVe(), info);
        System.out.println("@exportPDF: " + res);
        }
    }
    
        
        
    }
    

