/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ui;

import com.dao.DongVatDAO;
import com.mode.*;
import com.utils.Auth;
import com.utils.MsgBox;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class DongVatJDialog extends javax.swing.JDialog {

    /**
     * Creates new form DongVat
     */
    public DongVatJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jFileChooser1 = new javax.swing.JFileChooser();
        tabsDongvat = new javax.swing.JTabbedPane();
        pnlThongTin = new javax.swing.JPanel();
        lblDongVat = new javax.swing.JLabel();
        lblMaDV = new javax.swing.JLabel();
        lblTenDV = new javax.swing.JLabel();
        lblGioiTinh = new javax.swing.JLabel();
        lblPhanBo = new javax.swing.JLabel();
        lblDatDiem = new javax.swing.JLabel();
        lblSinhThai = new javax.swing.JLabel();
        lblSinhSan = new javax.swing.JLabel();
        lbltinhTrang = new javax.swing.JLabel();
        txtMaDV = new javax.swing.JTextField();
        txtTenDV = new javax.swing.JTextField();
        rdoDuc = new javax.swing.JRadioButton();
        rdoCaii = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtXuatSu = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtdatDiem = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtSinhThai = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtSinhSan = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtTinhTrang = new javax.swing.JTextArea();
        pnlChucNangChinhSua = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        pnlChucNangDieuHuong = new javax.swing.JPanel();
        btnFirst = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        lblHinh = new javax.swing.JLabel();
        btnThemAnh = new javax.swing.JButton();
        pnlAnh = new javax.swing.JPanel();
        lblAnh = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnTrangChu = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();
        btnThoat1 = new javax.swing.JButton();
        lblBLMaDV = new javax.swing.JLabel();
        lblBLTenDV = new javax.swing.JLabel();
        pnlDanhSach = new javax.swing.JPanel();
        lblDanhSachDongVat = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblDanhSachDV = new javax.swing.JTable();
        lblTimKiem = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Động Vật");

        lblDongVat.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lblDongVat.setForeground(new java.awt.Color(255, 51, 51));
        lblDongVat.setText("ĐỘNG VẬT");

        lblMaDV.setText("Mã Động Vật:");

        lblTenDV.setText("Tên Động Vật:");

        lblGioiTinh.setText("Giới tính:");

        lblPhanBo.setText("Xuất Sứ");

        lblDatDiem.setText("Đặc điểm:");

        lblSinhThai.setText("Sinh thái:");

        lblSinhSan.setText("Sinh sản:");

        lbltinhTrang.setText("Tình trạng:");

        buttonGroup1.add(rdoDuc);
        rdoDuc.setSelected(true);
        rdoDuc.setText("Đực");

        buttonGroup1.add(rdoCaii);
        rdoCaii.setText("Cái");

        txtXuatSu.setColumns(20);
        txtXuatSu.setRows(5);
        jScrollPane1.setViewportView(txtXuatSu);

        txtdatDiem.setColumns(20);
        txtdatDiem.setRows(5);
        jScrollPane2.setViewportView(txtdatDiem);

        txtSinhThai.setColumns(20);
        txtSinhThai.setRows(5);
        jScrollPane3.setViewportView(txtSinhThai);

        txtSinhSan.setColumns(20);
        txtSinhSan.setRows(5);
        jScrollPane4.setViewportView(txtSinhSan);

        txtTinhTrang.setColumns(20);
        txtTinhTrang.setRows(5);
        txtTinhTrang.setText("\n");
        jScrollPane5.setViewportView(txtTinhTrang);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        pnlChucNangChinhSua.add(btnThem);

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        pnlChucNangChinhSua.add(btnSua);

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        pnlChucNangChinhSua.add(btnXoa);

        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });
        pnlChucNangChinhSua.add(btnMoi);

        btnFirst.setText("|<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        pnlChucNangDieuHuong.add(btnFirst);

        btnPrev.setText("<<");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });
        pnlChucNangDieuHuong.add(btnPrev);

        btnNext.setText(">>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        pnlChucNangDieuHuong.add(btnNext);

        btnLast.setText(">|");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        pnlChucNangDieuHuong.add(btnLast);

        lblHinh.setText("Hình:");

        btnThemAnh.setText("Thêm ảnh");
        btnThemAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemAnhActionPerformed(evt);
            }
        });

        pnlAnh.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));

        javax.swing.GroupLayout pnlAnhLayout = new javax.swing.GroupLayout(pnlAnh);
        pnlAnh.setLayout(pnlAnhLayout);
        pnlAnhLayout.setHorizontalGroup(
            pnlAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 283, Short.MAX_VALUE)
            .addGroup(pnlAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))
        );
        pnlAnhLayout.setVerticalGroup(
            pnlAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
            .addGroup(pnlAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        );

        jToolBar1.setRollover(true);

        btnTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sticker/Brick house.png"))); // NOI18N
        btnTrangChu.setText("Trang Chủ");
        btnTrangChu.setFocusable(false);
        btnTrangChu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTrangChu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChuActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTrangChu);

        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sticker/Exit.png"))); // NOI18N
        btnDangXuat.setText("Đăng Xuất");
        btnDangXuat.setFocusable(false);
        btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuat.setMargin(new java.awt.Insets(2, 16, 2, 16));
        btnDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDangXuat);

        btnThoat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sticker/Stop.png"))); // NOI18N
        btnThoat1.setText("Thoát");
        btnThoat1.setFocusable(false);
        btnThoat1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThoat1.setMargin(new java.awt.Insets(2, 16, 2, 16));
        btnThoat1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThoat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoat1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnThoat1);

        lblBLMaDV.setForeground(new java.awt.Color(255, 0, 0));

        lblBLTenDV.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnlThongTinLayout = new javax.swing.GroupLayout(pnlThongTin);
        pnlThongTin.setLayout(pnlThongTinLayout);
        pnlThongTinLayout.setHorizontalGroup(
            pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addComponent(lblMaDV)
                        .addGap(18, 18, 18)
                        .addComponent(txtMaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTenDV)
                            .addComponent(lblGioiTinh)
                            .addComponent(lblPhanBo)
                            .addComponent(lblDatDiem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblBLMaDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlThongTinLayout.createSequentialGroup()
                                .addComponent(rdoDuc, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdoCaii, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtTenDV)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addComponent(lblBLTenDV, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))))
                .addGap(28, 28, 28)
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addComponent(lblSinhThai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3))
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addComponent(lblSinhSan)
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane4))
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbltinhTrang)
                            .addGroup(pnlThongTinLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lblHinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5)
                            .addGroup(pnlThongTinLayout.createSequentialGroup()
                                .addComponent(pnlAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnThemAnh)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThongTinLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(pnlChucNangChinhSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlChucNangDieuHuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(pnlThongTinLayout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(lblDongVat, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlThongTinLayout.setVerticalGroup(
            pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinLayout.createSequentialGroup()
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDongVat))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaDV)
                            .addComponent(txtMaDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSinhThai))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBLMaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTenDV)
                            .addComponent(txtTenDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lblBLTenDV, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGioiTinh)
                            .addComponent(rdoDuc)
                            .addComponent(rdoCaii)
                            .addComponent(lblSinhSan))
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlThongTinLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(lbltinhTrang))
                            .addGroup(pnlThongTinLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPhanBo)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(41, 41, 41)
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDatDiem)
                            .addComponent(lblHinh)))
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlThongTinLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(btnThemAnh))
                            .addGroup(pnlThongTinLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(pnlAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlChucNangChinhSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlChucNangDieuHuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tabsDongvat.addTab("Thông tin", pnlThongTin);

        lblDanhSachDongVat.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lblDanhSachDongVat.setForeground(new java.awt.Color(255, 51, 51));
        lblDanhSachDongVat.setText("DANH SÁCH ĐỘNG VẬT");

        tblDanhSachDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã ĐV", "Mã nhân viên", "Tên ĐV", "Phân bố", "Giới tính", "Đặt điểm", "Sinh thái", "Sinh sản", "Tình trạng", "Hình"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDanhSachDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachDVMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblDanhSachDV);

        lblTimKiem.setText("Tìm kiếm:");

        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlDanhSachLayout = new javax.swing.GroupLayout(pnlDanhSach);
        pnlDanhSach.setLayout(pnlDanhSachLayout);
        pnlDanhSachLayout.setHorizontalGroup(
            pnlDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDanhSachLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlDanhSachLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(lblDanhSachDongVat, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDanhSachLayout.createSequentialGroup()
                        .addComponent(lblTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimKiem)))
                .addContainerGap(346, Short.MAX_VALUE))
            .addGroup(pnlDanhSachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6)
                .addContainerGap())
        );
        pnlDanhSachLayout.setVerticalGroup(
            pnlDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDanhSachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDanhSachDongVat)
                .addGap(12, 12, 12)
                .addGroup(pnlDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabsDongvat.addTab("Danh Sách", pnlDanhSach);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabsDongvat)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabsDongvat)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemAnhActionPerformed
        this.themAnh();
    }//GEN-LAST:event_btnThemAnhActionPerformed

    private void tblDanhSachDVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachDVMouseClicked
        if(evt.getClickCount()==2){
           this.row = tblDanhSachDV.getSelectedRow();
           this.edit();
        }
    }//GEN-LAST:event_tblDanhSachDVMouseClicked

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        this.last();
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        this.next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        this.prev();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        this.first();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        this.clearForm();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        this.delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        this.update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        this.insert();
    }//GEN-LAST:event_btnThemActionPerformed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        this.fillTabledv();
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void btnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChuActionPerformed
        this.openTrangChu();
    }//GEN-LAST:event_btnTrangChuActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        this.dangXuat();
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnThoat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoat1ActionPerformed
        this.ketThuc();
    }//GEN-LAST:event_btnThoat1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DongVatJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DongVatJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DongVatJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DongVatJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DongVatJDialog dialog = new DongVatJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemAnh;
    private javax.swing.JButton btnThoat1;
    private javax.swing.JButton btnTrangChu;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblAnh;
    private javax.swing.JLabel lblBLMaDV;
    private javax.swing.JLabel lblBLTenDV;
    private javax.swing.JLabel lblDanhSachDongVat;
    private javax.swing.JLabel lblDatDiem;
    private javax.swing.JLabel lblDongVat;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JLabel lblMaDV;
    private javax.swing.JLabel lblPhanBo;
    private javax.swing.JLabel lblSinhSan;
    private javax.swing.JLabel lblSinhThai;
    private javax.swing.JLabel lblTenDV;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JLabel lbltinhTrang;
    private javax.swing.JPanel pnlAnh;
    private javax.swing.JPanel pnlChucNangChinhSua;
    private javax.swing.JPanel pnlChucNangDieuHuong;
    private javax.swing.JPanel pnlDanhSach;
    private javax.swing.JPanel pnlThongTin;
    private javax.swing.JRadioButton rdoCaii;
    private javax.swing.JRadioButton rdoDuc;
    private javax.swing.JTabbedPane tabsDongvat;
    private javax.swing.JTable tblDanhSachDV;
    private javax.swing.JTextField txtMaDV;
    private javax.swing.JTextArea txtSinhSan;
    private javax.swing.JTextArea txtSinhThai;
    private javax.swing.JTextField txtTenDV;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextArea txtTinhTrang;
    private javax.swing.JTextArea txtXuatSu;
    private javax.swing.JTextArea txtdatDiem;
    // End of variables declaration//GEN-END:variables
    DongVatDAO dao = new DongVatDAO();
    private void init() {
        this.setLocationRelativeTo(null);
        this.row = -1;
        this.updateStatus();
        this.fillTable();
    }
    int row=-1;
    void openTrangChu(){
        if(Auth.isLogin()){
            TrangchuJFrame tc = new TrangchuJFrame();
            tc.setVisible(true);
            this.dispose();
        }else{
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }
    private void dangXuat(){
        Auth.clear();
        this.dispose();
        new DangNhapJDialog(null, true).setVisible(true);
    }
    void ketThuc(){
        if(MsgBox.confirm(this, "Bạn muốn kết thúc làm việc?")){
            System.exit(0);
        }
    }
    void insert() {
        //gọi nút btnThem

        try {
            batloi();
            dongvat dv = getForm();//lấy nhân viên từ form
            dao.insert(dv);
            //sau khi insert thành công, cập nhật lại bảng
            this.fillTable();
            //xóa form
            this.clearForm();
            MsgBox.alert(this, "Thêm mới thành công!");
        } catch (Exception e) {
            MsgBox.alert(this, "Thêm mới thất bại");
        }
    }
    void batloi(){
        if(txtMaDV.getText().length()==0){
            lblBLMaDV.setText("* Vul lòng nhập mã Động Vật");
        }else if(txtTenDV.getText().length()==0){
            lblBLTenDV.setText("* Vui lòng nhập tên Động vật");
        }
    }
    void update() {
        //cap nhat
        //btn sửa

        try {
            batloi();
            dongvat dv = getForm();
            dao.update(dv);
            this.fillTable();
            MsgBox.alert(this, "Cập nhật thành công!!!");
        } catch (Exception e) {
            MsgBox.alert(this, "Cập nhật thất bại!!!");
        }
    }

    void delete() {
        try {
            batloi();
            if (MsgBox.confirm(this, "Bạn thực sự muốn xóa động vật này?")) {
                String manv = txtMaDV.getText();
                try {
                    dao.delete(manv);
                    this.fillTable();
                    this.clearForm();
                    MsgBox.alert(this, "Xóa thành công");
                } catch (Exception e) {
                    MsgBox.alert(this, "Xóa thất bại");
                }
            }
        } catch (Exception e) {
        }

    }
    void clearForm(){
        //làm trắng form
        this.setForm(new dongvat());
        lblAnh.setIcon(null);
        this.row=-1;
        this.updateStatus();
    }
    void edit(){
        String madv = (String) tblDanhSachDV.getValueAt(this.row, 0);
        dongvat dv = dao.selectById(madv);
        this.setForm(dv);
        this.updateStatus();
        tabsDongvat.setSelectedIndex(0);
    } 
    void first(){
        this.row=0;
        this.edit();
    }
    void prev(){
        if(this.row>0){
            this.row--;
            this.edit();
        }
    }
    void next(){
        if(this.row<tblDanhSachDV.getRowCount()-1){
            this.row++;
            this.edit();
        }
    }
    void last(){
        this.row=tblDanhSachDV.getRowCount()-1;
        this.edit();
    }
    void fillTable(){
        //Đỗ dữ liệu lên table
        DefaultTableModel model = (DefaultTableModel)tblDanhSachDV.getModel();
        model.setRowCount(0);//xóa tất cả các hàng trên JTable;
        try {
            List<dongvat> list = dao.selectAll(); //đọc dữ liệu trên CSDL 
            for(dongvat dv : list){
                Object[] row = {dv.getMaDV(),dv.getMaNV(),dv.getTenDV(),dv.getXuatSu(),dv.getGioitinh(),dv.getDatDiem(),dv.getSinhThai(),dv.getSinhSan(),dv.getTinhTrang(),dv.getHinh()};
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu");
        }
    }
    void setForm(dongvat dv){
        //hiểm thị động vật lên form
        txtMaDV.setText(dv.getMaDV());
        txtTenDV.setText(dv.getTenDV());
        rdoDuc.setSelected(dv.getGioitinh());
        rdoCaii.setSelected(!dv.getGioitinh());
        txtXuatSu.setText(dv.getXuatSu());
        txtdatDiem.setText(dv.getDatDiem());
        txtSinhThai.setText(dv.getSinhThai());
        txtSinhSan.setText(dv.getSinhSan());
        txtTinhTrang.setText(dv.getTinhTrang());
        if(dv.getHinh()!=null){
            lblAnh.setToolTipText(dv.getHinh());
            ImageIcon resizedImage = resize(read(dv.getHinh()),280,160);
            lblAnh.setIcon(resizedImage);
        }else{
            lblAnh.setIcon(null);
        }
    }
    dongvat getForm(){
        //them dong vat tu form
        dongvat dv = new dongvat();
        dv.setMaDV(txtMaDV.getText());
        dv.setMaNV(Auth.user.getManv());
        dv.setTenDV(txtTenDV.getText());
        dv.setXuatSu(txtXuatSu.getText());
        dv.setGioitinh(rdoDuc.isSelected());
        dv.setDatDiem(txtdatDiem.getText());
        dv.setSinhThai(txtSinhThai.getText());
        dv.setSinhSan(txtSinhSan.getText());
        dv.setTinhTrang(txtTinhTrang.getText());
        dv.setHinh(lblAnh.getToolTipText());
        return dv;
    }
    void updateStatus(){
        //cập nhật trạng thái các nút
        boolean edit = (this.row>=0);
        boolean first = (this.row==0);
        boolean last = (this.row == tblDanhSachDV.getRowCount()-1);
        
        //trạng thái form
        txtMaDV.setEditable(!edit);
        btnThem.setEnabled(!edit);
        btnSua.setEnabled(edit);
        btnXoa.setEnabled(edit);
        
        //Trạng thái điều hướng
        btnFirst.setEnabled(edit && !first);
        btnPrev.setEnabled(edit && !first);
        btnNext.setEnabled(edit && !last);
        btnLast.setEnabled(edit && !last);
    }

    public static ImageIcon read(String fileName){
        File path = new File("hinhDV",fileName);
        return new ImageIcon(path.getAbsolutePath());
    }
    public void  UpHinh(File src){
        File dst = new File("hinhDV",src.getName());
        //Tạo thư muc logo nếu chưa tồn tại
        if(!dst.getParentFile().exists()){
            dst.getParentFile().mkdirs();
        }
        try{
            Path from = Paths.get(src.getAbsolutePath());
            Path to = Paths.get(dst.getAbsolutePath());
            //copy file vào thư mục logos
            Files.copy(from,to,StandardCopyOption.REPLACE_EXISTING); 
        }catch(Exception e){
            throw new RuntimeException(e);
        }
    }
    public static ImageIcon resize(ImageIcon img, int width, int height){
        BufferedImage bi = new BufferedImage(width, height, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = (Graphics2D) bi.createGraphics();
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
        g2d.drawImage(img.getImage(), 0, 0, width, height, null);
        g2d.dispose();
        return new ImageIcon(bi);
    }
    void themAnh(){
        if(jFileChooser1.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            File file = jFileChooser1.getSelectedFile();
            UpHinh(file);//lưu hình vào thư mục Logos
            ImageIcon resizedImage = resize(read(file.getName()),280,160);//đọc hình tư logos và định dạng kích thước
            lblAnh.setIcon(resizedImage);//hiểm thị ảnh lên form
            lblAnh.setToolTipText(file.getName());// giữ ghi nhớ tên hình trong tooltip
        }
    }
    void fillTabledv(){
        //Đỗ dữ liệu lên table
        DefaultTableModel model = (DefaultTableModel)tblDanhSachDV.getModel();
        model.setRowCount(0);//xóa tất cả các hàng trên JTable;
        String mdv = txtTimKiem.getText();
        try {
            List<dongvat> list = dao.selectBytk(mdv); //đọc dữ liệu trên CSDL 
            for(dongvat dv : list){
                Object[] row = {dv.getMaDV(),dv.getMaNV(),dv.getTenDV(),dv.getXuatSu(),dv.getGioitinh(),dv.getDatDiem(),dv.getSinhThai(),dv.getSinhSan(),dv.getTinhTrang(),dv.getHinh()};
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu");
        }
    }
}
