/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ui;

import com.utils.Auth;
import com.utils.MsgBox;
import com.utils.XImage;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author hp
 */
public class TrangchuJFrame extends javax.swing.JFrame {

    /**
     * Creates new form Manuchinh
     */
    public TrangchuJFrame() {
        initComponents();
        init();
        this.setIconImage(XImage.getAppIcon());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblQuanLyST = new javax.swing.JLabel();
        lblngay = new javax.swing.JLabel();
        tbaCongCu = new javax.swing.JToolBar();
        btnQLNV = new javax.swing.JButton();
        btnQLBanVe = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btnQLDongVat = new javax.swing.JButton();
        btnThemTaiKhoang = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btnHuongDan = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();
        btnKetThuc = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuHeThong = new javax.swing.JMenu();
        mniDangXuat = new javax.swing.JMenuItem();
        mniThoat = new javax.swing.JMenuItem();
        mniThemTK = new javax.swing.JMenuItem();
        mniDoiMatKhau = new javax.swing.JMenuItem();
        mnuQuanLy = new javax.swing.JMenu();
        mniNhanVien = new javax.swing.JMenuItem();
        mniDongVat = new javax.swing.JMenuItem();
        mniQLBanVe = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniBanVe = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuThongKe = new javax.swing.JMenu();
        mniThuNhap = new javax.swing.JMenuItem();
        mniChiTieu = new javax.swing.JMenuItem();
        mniSoLuong = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trang chủ");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Icon/buc-tranh-dai-dien-cho-vuong-bach-thu-201411.jpg"))); // NOI18N
        getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 30));

        lblQuanLyST.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sticker/Dog.png"))); // NOI18N
        lblQuanLyST.setText("Quản lý sở thú");

        lblngay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sticker/Alarm.png"))); // NOI18N
        lblngay.setText("ngày");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQuanLyST)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 676, Short.MAX_VALUE)
                .addComponent(lblngay)
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuanLyST)
                    .addComponent(lblngay)))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        tbaCongCu.setBackground(new java.awt.Color(204, 255, 204));
        tbaCongCu.setRollover(true);

        btnQLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sticker/Clien list.png"))); // NOI18N
        btnQLNV.setText("Quản lý nhân viên");
        btnQLNV.setFocusable(false);
        btnQLNV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLNV.setMargin(new java.awt.Insets(2, 15, 2, 15));
        btnQLNV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLNVActionPerformed(evt);
            }
        });
        tbaCongCu.add(btnQLNV);

        btnQLBanVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sticker/Dollar.png"))); // NOI18N
        btnQLBanVe.setText("Quản lý bán vé");
        btnQLBanVe.setFocusable(false);
        btnQLBanVe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLBanVe.setMargin(new java.awt.Insets(2, 15, 2, 15));
        btnQLBanVe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLBanVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLBanVeActionPerformed(evt);
            }
        });
        tbaCongCu.add(btnQLBanVe);
        tbaCongCu.add(jSeparator6);

        btnQLDongVat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sticker/Cat.png"))); // NOI18N
        btnQLDongVat.setText("Quản lý động vật");
        btnQLDongVat.setFocusable(false);
        btnQLDongVat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLDongVat.setMargin(new java.awt.Insets(2, 15, 2, 15));
        btnQLDongVat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLDongVat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLDongVatActionPerformed(evt);
            }
        });
        tbaCongCu.add(btnQLDongVat);

        btnThemTaiKhoang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sticker/Add.png"))); // NOI18N
        btnThemTaiKhoang.setText("Thêm tài khoản");
        btnThemTaiKhoang.setFocusable(false);
        btnThemTaiKhoang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThemTaiKhoang.setMargin(new java.awt.Insets(2, 15, 2, 15));
        btnThemTaiKhoang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThemTaiKhoang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTaiKhoangActionPerformed(evt);
            }
        });
        tbaCongCu.add(btnThemTaiKhoang);
        tbaCongCu.add(jSeparator7);

        btnHuongDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sticker/Globe.png"))); // NOI18N
        btnHuongDan.setText("Hướng dẫn");
        btnHuongDan.setFocusable(false);
        btnHuongDan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHuongDan.setMargin(new java.awt.Insets(2, 15, 2, 15));
        btnHuongDan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHuongDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuongDanActionPerformed(evt);
            }
        });
        tbaCongCu.add(btnHuongDan);

        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sticker/Log out.png"))); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setFocusable(false);
        btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuat.setMargin(new java.awt.Insets(2, 15, 2, 15));
        btnDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        tbaCongCu.add(btnDangXuat);

        btnKetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sticker/No.png"))); // NOI18N
        btnKetThuc.setText("Kết thúc");
        btnKetThuc.setFocusable(false);
        btnKetThuc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKetThuc.setMargin(new java.awt.Insets(2, 15, 2, 15));
        btnKetThuc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKetThucActionPerformed(evt);
            }
        });
        tbaCongCu.add(btnKetThuc);

        getContentPane().add(tbaCongCu, java.awt.BorderLayout.PAGE_START);

        jMenuBar1.setBackground(new java.awt.Color(153, 255, 153));

        mnuHeThong.setText("Hệ thống");

        mniDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sticker/Exit.png"))); // NOI18N
        mniDangXuat.setText("Đăng xuất");
        mniDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangXuatActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDangXuat);

        mniThoat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mniThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sticker/No.png"))); // NOI18N
        mniThoat.setText("Thoát");
        mniThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniThoatActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniThoat);

        mniThemTK.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniThemTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sticker/Add.png"))); // NOI18N
        mniThemTK.setText("Thêm tài khoản");
        mniThemTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniThemTKActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniThemTK);

        mniDoiMatKhau.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sticker/Refresh.png"))); // NOI18N
        mniDoiMatKhau.setText("Đổi mật khẩu");
        mniDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoiMatKhauActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDoiMatKhau);

        jMenuBar1.add(mnuHeThong);

        mnuQuanLy.setText("Quản lý");
        mnuQuanLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuQuanLyActionPerformed(evt);
            }
        });

        mniNhanVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sticker/Clien list.png"))); // NOI18N
        mniNhanVien.setText("Quản Lý Nhân Viên");
        mniNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNhanVienActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniNhanVien);

        mniDongVat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDongVat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sticker/Cat.png"))); // NOI18N
        mniDongVat.setText("Quản Lý Động Vật");
        mniDongVat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDongVatActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniDongVat);

        mniQLBanVe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniQLBanVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sticker/Price list.png"))); // NOI18N
        mniQLBanVe.setText("Quản Lý Bán vé");
        mniQLBanVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLBanVeActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniQLBanVe);
        mnuQuanLy.add(jSeparator1);

        mniBanVe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniBanVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sticker/Add to basket.png"))); // NOI18N
        mniBanVe.setText("Bán Vé");
        mniBanVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBanVeActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniBanVe);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sticker/Coins.png"))); // NOI18N
        jMenuItem1.setText("Chi Tiêu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuQuanLy.add(jMenuItem1);

        jMenuBar1.add(mnuQuanLy);

        mnuThongKe.setText("Thông kê");

        mniThuNhap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniThuNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sticker/Coins.png"))); // NOI18N
        mniThuNhap.setText("Thu nhập");
        mniThuNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniThuNhapActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniThuNhap);

        mniChiTieu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniChiTieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sticker/Full basket.png"))); // NOI18N
        mniChiTieu.setText("Chi tiêu");
        mniChiTieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniChiTieuActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniChiTieu);

        mniSoLuong.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniSoLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sticker/Statistics.png"))); // NOI18N
        mniSoLuong.setText("Sô lượng nhân viên và động vật");
        mniSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSoLuongActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniSoLuong);

        jMenuBar1.add(mnuThongKe);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangXuatActionPerformed
        this.dangXuat();
    }//GEN-LAST:event_mniDangXuatActionPerformed

    private void mniThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniThoatActionPerformed
        this.ketThuc();
    }//GEN-LAST:event_mniThoatActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        this.dangXuat();
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnQLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLNVActionPerformed
        this.openNhanVien();
    }//GEN-LAST:event_btnQLNVActionPerformed

    private void btnQLDongVatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLDongVatActionPerformed
        this.openDongVat();
    }//GEN-LAST:event_btnQLDongVatActionPerformed

    private void mniNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNhanVienActionPerformed
        this.openNhanVien();
    }//GEN-LAST:event_mniNhanVienActionPerformed

    private void mniDongVatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDongVatActionPerformed
        this.openDongVat();
    }//GEN-LAST:event_mniDongVatActionPerformed

    private void mnuQuanLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuQuanLyActionPerformed
        this.openDongVat();
    }//GEN-LAST:event_mnuQuanLyActionPerformed

    private void btnKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKetThucActionPerformed
        this.ketThuc();
    }//GEN-LAST:event_btnKetThucActionPerformed

    private void mniThemTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniThemTKActionPerformed
        this.openThemTK();
    }//GEN-LAST:event_mniThemTKActionPerformed

    private void btnThemTaiKhoangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTaiKhoangActionPerformed
        this.openThemTK();
    }//GEN-LAST:event_btnThemTaiKhoangActionPerformed

    private void mniDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoiMatKhauActionPerformed
        this.openDoiMatKhau();
    }//GEN-LAST:event_mniDoiMatKhauActionPerformed

    private void btnQLBanVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLBanVeActionPerformed
        this.openQLBanVe();
    }//GEN-LAST:event_btnQLBanVeActionPerformed

    private void mniQLBanVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLBanVeActionPerformed
        this.openQLBanVe();
    }//GEN-LAST:event_mniQLBanVeActionPerformed

    private void mniBanVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBanVeActionPerformed
        this.openBanVe();
    }//GEN-LAST:event_mniBanVeActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.openChiTieu();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mniThuNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniThuNhapActionPerformed
        this.openThongKe(0);
    }//GEN-LAST:event_mniThuNhapActionPerformed

    private void mniChiTieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniChiTieuActionPerformed
        this.openThongKe(1);
    }//GEN-LAST:event_mniChiTieuActionPerformed

    private void mniSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSoLuongActionPerformed
        this.openThongKe(2);
    }//GEN-LAST:event_mniSoLuongActionPerformed

    private void btnHuongDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuongDanActionPerformed
        this.openHuongDan();
    }//GEN-LAST:event_btnHuongDanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangchuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangchuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangchuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangchuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangchuJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnHuongDan;
    private javax.swing.JButton btnKetThuc;
    private javax.swing.JButton btnQLBanVe;
    private javax.swing.JButton btnQLDongVat;
    private javax.swing.JButton btnQLNV;
    private javax.swing.JButton btnThemTaiKhoang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JLabel lblQuanLyST;
    private javax.swing.JLabel lblngay;
    private javax.swing.JMenuItem mniBanVe;
    private javax.swing.JMenuItem mniChiTieu;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniDoiMatKhau;
    private javax.swing.JMenuItem mniDongVat;
    private javax.swing.JMenuItem mniNhanVien;
    private javax.swing.JMenuItem mniQLBanVe;
    private javax.swing.JMenuItem mniSoLuong;
    private javax.swing.JMenuItem mniThemTK;
    private javax.swing.JMenuItem mniThoat;
    private javax.swing.JMenuItem mniThuNhap;
    private javax.swing.JMenu mnuHeThong;
    private javax.swing.JMenu mnuQuanLy;
    private javax.swing.JMenu mnuThongKe;
    private javax.swing.JToolBar tbaCongCu;
    // End of variables declaration//GEN-END:variables

    void init(){
        this.setLocationRelativeTo(null);
        this.starDongHo();
    }
    
    private void starDongHo() {
        new Timer(1000, new ActionListener() {
            @Override
            //cứ 1000ms sẽ gọi hàm 1 lần
            public void actionPerformed(ActionEvent e) {
                // lấy thời gian hệ thống ra
                Date now = new Date();
                //Chuyển đổi sang chuổi giờ phút giây
                SimpleDateFormat fm = new SimpleDateFormat("dd/MM/yyyy  hh:mm:ss a");
                
                lblngay.setText(fm.format(new Date()));
                //a: sáng chiều
                //String text = format.format(now);
               // lblngay.setText(text);
            }
        }).start();
    }
    private void dangXuat(){
        Auth.clear();
        this.dispose();
        new DangNhapJDialog(this, true).setVisible(true);
    }
    private void ketThuc(){
        if(MsgBox.confirm(this, "Bạn muốn kết thúc làm việc?")){
            System.exit(0);
        }
    }
    private void openChiTieu(){
        if(Auth.isLogin()){
            ChiTieuJFrame ct = new ChiTieuJFrame();
            ct.setVisible(true);
            this.dispose();
        }else{
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }
    private void openNhanVien() {
        if(Auth.isLogin()){
            this.dispose();
            new QLNhanVienJDialog(this, true).setVisible(true);
        }else{
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }
    private void openDoiMatKhau() {
        if(Auth.isLogin()){
            new DoiMatKhauJDialog(this, true).setVisible(true);
        }else{
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }
    private void openDongVat() {
        if(Auth.isLogin()){
            this.dispose();
            new DongVatJDialog(this, true).setVisible(true);
            
        }else{
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }
    private void openThemTK(){
        if(Auth.isLogin()){
            new TaoTaiKhoangJDialog(this, true).setVisible(true);
        }else{
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }
    private void openQLBanVe(){
        if(Auth.isLogin()){
            QuanLyBanVeJFrame QLBV = new QuanLyBanVeJFrame();
            this.dispose();
            QLBV.setVisible(true);
            
        }else{
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }
    private void openBanVe(){
        if(Auth.isLogin()){
            BanVeJFrame bv = new BanVeJFrame();
            this.dispose();
            bv.setVisible(true);
            
        }else{
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }
    
    private void openThongKe(int index) {
        if (Auth.isLogin()) {
            ThongKeJFrame tkwin = new ThongKeJFrame();
            this.dispose();
            tkwin.selectTab(index);
            tkwin.setVisible(true);
            
        }else{
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }
     private void openHuongDan(){
        try {
            Desktop.getDesktop().browse(new File("help/Gardens.html").toURI());
        } catch (Exception e) {
            MsgBox.alert(this, "Không tìm thấy file hướng dẫn!");
        }
    }
}
